# Generated by Django 3.0.5 on 2020-05-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=20)),
                ('house_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(max_length=10)),
                ('index', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.ClientAddress')),
                ('client_names', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.ClientNames')),
            ],
        ),
    ]
