# Generated by Django 3.0.5 on 2020-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_clientaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnames',
            name='name_of_organization',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
