# Generated by Django 3.0.5 on 2020-05-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200508_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnames',
            name='name_of_organization',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
